spring:
  config:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/${db}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10 # 풀 크기 조정
      max-lifetime: 30000
      connection-timeout: 3000 # 다임아웃 시간 설정
#      leak-detection-threshold: 200 # 연결 누수 감지
      username: ${user}
      password: ${pw}
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  data:
    redis:
      host: localhost
      port: 6380