# 배포용 yml db 수정예정
spring:
  config:
    active: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://PROD_URL:3306/${db}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10 # 풀 크기 조정
      max-lifetime: 30000
      connection-timeout: 3000 # 다임아웃 시간 설정
#      leak-detection-threshold: 200 # 연결 누수 감지
      username: PROD_USER_NAME
      password: PROD_PASSWORD
    jpa:
      hibernate:
        ddl-auto: none
  data:
    redis:
      host: PROD_URL
      port: 6380